export { assoc } from './assoc'
export { dissoc } from './dissoc'
export { isEmpty } from './isEmpty'
export { isNull } from './isNull'
export { prop } from './prop'
export { propOr } from './propOr'
export { set } from './set'
