export const functionNames = {
  avg: 'avg',
  categoryItemProp: 'categoryItemProp',
  count: 'count',
  distance: 'distance',
  first: 'first',
  geoPolygon: 'geoPolygon',
  includes: 'includes',
  index: 'index',
  isEmpty: 'isEmpty',
  last: 'last',
  ln: 'ln',
  log10: 'log10',
  max: 'max',
  min: 'min',
  now: 'now',
  parent: 'parent',
  pow: 'pow',
  sum: 'sum',
  taxonProp: 'taxonProp',
  uuid: 'uuid',
}
