branch-defaults:
  default:
    environment: rstudioproxy-default-env
    group_suffix: null
global:
  application_name: RStudioProxy_b
  branch: null
  default_ec2_keyname: LambdaInstance
  default_platform: Node.js 12
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: openforis
  repository: null
  sc: null
  workspace_type: Application
