queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=DeepScan
      
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
  - name: automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update: {}
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
