pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update: {}
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
