approvedGitRepositories:
  - "**"
enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: 0
npmPreapprovedPackages:
  - "@openforis/arena-core"
  - "@openforis/arena-server"
npmScopes:
  openforis:
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com"
yarnPath: .yarn/releases/yarn-4.18.0.cjs

