approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@openforis/arena-core"
  - "@openforis/arena-server"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
