approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@openforis/arena-server"

npmScopes:
  openforis:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
