import * as Survey from '../../../../../core/survey/survey'
import * as NodeDef from '../../../../../core/survey/nodeDef'

import { TableDataNodeDef } from '../../../../../common/model/db'

/**
 * Create a nodeDef data table.
 *
 * @param {object} params - The query parameters.
 * @param {Survey} params.survey - The survey.
 * @param {NodeDef} params.nodeDef - The nodeDef to create the data table for.
 * @param {pgPromise.IDatabase} client - The data base client.
 *
 * @returns {Promise<null|*>} - The result promise.
 */
export const createDataTable = async ({ survey, nodeDef }, client) => {
  if (NodeDef.isVirtual(nodeDef)) {
    return null
  }

  const tableDataNodeDef = new TableDataNodeDef(survey, nodeDef)
  const constraintFkParent = tableDataNodeDef.getConstraintFkParent()
  const constraintFkRecord = tableDataNodeDef.getConstraintFkRecord()

  return client.query(
    `CREATE TABLE
        ${tableDataNodeDef.nameQualified}
      (
        ${tableDataNodeDef.getColumnsWithType().join(', ')},
        ${tableDataNodeDef.getConstraintUuidUnique()},
        ${constraintFkParent ? `${constraintFkParent}, ` : ''}
        ${constraintFkRecord ? `${constraintFkRecord}, ` : ''}
        PRIMARY KEY (${TableDataNodeDef.columnSet.id})
      )`
  )
}

/**
 * Returns the columns to index in a nodeDef data table.
 * Root table: record uuid (filter by record, cascade delete from record table) and record owner uuid (filter by owner).
 * Other tables: parent uuid (joins with parent tables and cascade delete from parent table).
 * @param {NodeDef} nodeDef - The nodeDef of the data table.
 * @returns {string[]} - The names of the columns to index.
 */
const _getIndexedColumnNames = (nodeDef) => {
  const { columnSet } = TableDataNodeDef
  return NodeDef.isRoot(nodeDef) ? [columnSet.recordUuid, columnSet.recordOwnerUuid] : [columnSet.parentUuid]
}

/**
 * Create the indexes of a nodeDef data table.
 * It should be invoked after the table has been populated, to speed up the bulk insert.
 * @param {object} params - The query parameters.
 * @param {Survey} params.survey - The survey.
 * @param {NodeDef} params.nodeDef - The nodeDef of the data table.
 * @param {pgPromise.IDatabase} client - The data base client.
 * @returns {Promise<void>} - The result promise.
 */
export const createDataTableIndexes = async ({ survey, nodeDef }, client) => {
  if (NodeDef.isVirtual(nodeDef)) {
    return
  }
  const tableDataNodeDef = new TableDataNodeDef(survey, nodeDef)
  for (const columnName of _getIndexedColumnNames(nodeDef)) {
    // index name is generated by PostgreSQL (unique and within the max identifier length)
    await client.query(`CREATE INDEX ON ${tableDataNodeDef.nameQualified} (${columnName})`)
  }
}
