version: '3.4'

services:

  app_server:
    ports:
      - "9990:9090"
    build:
      context: ..
      dockerfile: Dockerfile
      target: arena-server
    environment:
      TEMP_FOLDER: /tmp/arena_upload
      ANALYSIS_OUTPUT_DIR: /tmp/arena_analysis
    image: of-arena-server
  web:
    depends_on:
      - app_server
    ports:
      - "9880:80"
    build:
      context: ..
      dockerfile: Dockerfile
      target: arena-web
    environment:
      ARENA_HOST: app_server:9090
    image: of-arena-web
