/**
 * Service for the natural-language → Data Explorer query feature.
 *
 * Pipeline:
 *   1. Load the survey (draft node defs, like the Data Explorer query execution does).
 *   2. Build the prompt with a compact schema description (entities, attributes,
 *      dimension / measure eligibility) and the user's request.
 *   3. Call `modelClient.generate` (plain text), parse the JSON tolerantly and
 *      validate its shape with Zod.
 *   4. Resolve the node def names into UUIDs and validate them against the
 *      Data Explorer rules (`@common/model/query/queryNodeDefs`); parse and
 *      check the filter expression and the sort criteria.
 *   5. On any failure, retry the prompt ONCE with the errors fed back.
 *   6. Return the query (ready to be set in the Data Explorer) and a short explanation of it.
 */
import { z } from 'zod'

import * as Authorizer from '@core/auth/authorizer'
import * as Expression from '@core/expressionParser/expression'
import * as Survey from '@core/survey/survey'
import * as NodeDef from '@core/survey/nodeDef'
import * as StringUtils from '@core/stringUtils'
import SystemError from '@core/systemError'
import { Query, QueryNodeDefs, SortCriteria } from '@common/model/query'
import { ColumnNodeDef } from '@common/model/db/tables/dataNodeDef'

import * as Log from '@server/log/log'
import * as SurveyManager from '@server/modules/survey/manager/surveyManager'

import * as ModelClient from './modelClient'
import { buildDataQueryGeneratePrompt } from './prompts/dataQueryGenerate'
import { parseJsonResponse } from './responseParsers'

const logger = Log.getLogger('AiDataQueryGenerateService')

const MAX_DESCRIPTION_LEN = 2000
const MAX_LANG_CODE_LEN = 16

const nullableStringArray = z
  .array(z.string())
  .nullish()
  .transform((value) => value ?? [])

const AiResultSchema = z.object({
  entity: z.string(),
  mode: z.enum([Query.modes.raw, Query.modes.aggregate]),
  attributes: nullableStringArray,
  dimensions: nullableStringArray,
  measures: z
    .array(z.object({ attribute: z.string(), functions: z.array(z.string()) }))
    .nullish()
    .transform((value) => value ?? []),
  filter: z.string().nullish(),
  sort: z
    .array(z.object({ attribute: z.string(), order: z.string().nullish() }))
    .nullish()
    .transform((value) => value ?? []),
  explanation: z.string().nullish(),
})

type AiResult = z.infer<typeof AiResultSchema>

const aggregateFunctions: string[] = Object.values(Query.DEFAULT_AGGREGATE_FUNCTIONS)

/**
 * Visits every node of a parsed expression, calling the visitor on each of them.
 * @param {object} node - The expression node.
 * @param {Function} visitor - Function called with (node, parent).
 * @param {object} [parent] - The parent node.
 * @returns {void}
 */
const visitExpression = (node, visitor, parent = null) => {
  if (!node || typeof node !== 'object') return
  if (Array.isArray(node)) {
    node.forEach((item) => visitExpression(item, visitor, parent))
    return
  }
  if (node.type) visitor(node, parent)
  Object.values(node).forEach((value) => {
    if (value && typeof value === 'object') visitExpression(value, visitor, node)
  })
}

/**
 * Parses and validates the filter expression generated by the model.
 * Identifiers must be column names of the attributes available to the query entity.
 * Single-quoted string literals are converted to double-quoted ones (what the SQL conversion expects).
 * @param {object} params - The parameters.
 * @param {string} params.filter - The filter expression (SQL mode syntax).
 * @param {Set<string>} params.allowedColumnNames - The column names that can be referenced.
 * @param {string[]} params.errors - Errors array to populate.
 * @returns {object|null} - The parsed expression, or null if not valid.
 */
const parseFilter = ({ filter, allowedColumnNames, errors }) => {
  let expr
  try {
    expr = Expression.fromString(filter, Expression.modes.sql)
  } catch (error) {
    errors.push(`filter "${filter}" cannot be parsed: ${error?.message ?? error}`)
    return null
  }
  let valid = true
  visitExpression(expr, (node, parent) => {
    if (node.type === Expression.types.Identifier) {
      const isCallee = parent?.type === Expression.types.CallExpression && parent.callee === node
      if (!isCallee && !allowedColumnNames.has(node.name)) {
        errors.push(`filter references unknown column "${node.name}"`)
        valid = false
      }
    } else if (node.type === Expression.types.Literal && typeof node.value === 'string') {
      node.raw = JSON.stringify(node.value)
    }
  })
  if (!valid) return null
  try {
    // validate the conversion to SQL (e.g. unsupported functions)
    Expression.toSql(expr)
  } catch (error) {
    errors.push(`filter "${filter}" is not supported: ${error?.message ?? error}`)
    return null
  }
  return expr
}

/**
 * Converts the (already parsed) model answer into a Data Explorer query, validating every node def reference.
 * @param {object} params - The parameters.
 * @param {object} params.survey - The survey.
 * @param {string} params.cycle - The survey cycle.
 * @param {string} params.lang - The language used for the sort criteria labels.
 * @param {object} params.aiResult - The model answer (validated by the Zod schema).
 * @param {boolean} [params.includeAnalysis] - Whether analysis attributes can be used.
 * @returns {{query: object|null, errors: string[]}} - The query (null if there are errors) and the validation errors.
 */
export const toQuery = ({
  survey,
  cycle,
  lang,
  aiResult,
  includeAnalysis = false,
}: {
  survey: any
  cycle: string
  lang: string
  aiResult: AiResult
  includeAnalysis?: boolean
}) => {
  const errors: string[] = []

  const entityDefs = QueryNodeDefs.getQueryableEntityDefs({ survey, cycle })
  const entityDef = entityDefs.find((nodeDef) => NodeDef.getName(nodeDef) === aiResult.entity)
  if (!entityDef) {
    errors.push(`entity "${aiResult.entity}" not found; valid entities: ${entityDefs.map(NodeDef.getName).join(', ')}`)
    return { query: null, errors }
  }
  const entityName = NodeDef.getName(entityDef)
  const modeAggregate = aiResult.mode === Query.modes.aggregate

  const resolveNames = ({ names, candidates, kind }) =>
    names.reduce((acc, name) => {
      const nodeDef = candidates.find((candidate) => NodeDef.getName(candidate) === name)
      if (nodeDef) {
        if (!acc.includes(nodeDef)) acc.push(nodeDef)
      } else {
        const existing = Survey.findNodeDefByName(name)(survey)
        errors.push(
          existing ? `"${name}" cannot be used as ${kind} for entity "${entityName}"` : `attribute "${name}" not found`
        )
      }
      return acc
    }, [])

  let query = Query.create({ entityDefUuid: NodeDef.getUuid(entityDef) })
  // columns (attributes or dimensions) that can be used for sorting
  let sortableDefs = []

  if (modeAggregate) {
    query = Query.assocMode(Query.modes.aggregate)(query)

    const dimensionDefs = resolveNames({
      names: aiResult.dimensions,
      candidates: QueryNodeDefs.getDimensionAttributeDefs({ survey, entityDef, cycle, includeAnalysis }),
      kind: 'dimension',
    })
    if (dimensionDefs.length === 0 && aiResult.dimensions.length === 0) {
      errors.push('aggregate mode requires at least one dimension')
    }
    query = Query.assocDimensions(dimensionDefs.map(NodeDef.getUuid))(query)
    sortableDefs = dimensionDefs

    const measureCandidates = QueryNodeDefs.getMeasureAttributeDefs({ survey, entityDef, cycle, includeAnalysis })
    const measures = {}
    aiResult.measures.forEach(({ attribute, functions }) => {
      const isEntityFrequency = attribute === entityName
      const measureDef = isEntityFrequency
        ? entityDef
        : resolveNames({ names: [attribute], candidates: measureCandidates, kind: 'measure' })[0]
      if (!measureDef) return
      if (functions.length === 0) {
        errors.push(`measure "${attribute}" has no aggregate functions`)
        return
      }

      const allowedFunctions = isEntityFrequency ? [Query.DEFAULT_AGGREGATE_FUNCTIONS.cnt] : aggregateFunctions
      const invalidFunctions = functions.filter((fn) => !allowedFunctions.includes(fn))
      if (invalidFunctions.length > 0) {
        errors.push(
          `invalid aggregate function(s) ${invalidFunctions.join(', ')} for measure "${attribute}"; allowed: ${allowedFunctions.join(', ')}`
        )
      }
      const validFunctions = [...new Set(functions.filter((fn) => allowedFunctions.includes(fn)))]
      if (validFunctions.length > 0) {
        const measureDefUuid = NodeDef.getUuid(measureDef)
        measures[measureDefUuid] = [...new Set([...(measures[measureDefUuid] ?? []), ...validFunctions])]
      }
    })
    if (aiResult.measures.length === 0) {
      errors.push('aggregate mode requires at least one measure')
    }
    query = Query.assocMeasures(measures)(query)
  } else {
    const attributeDefs = resolveNames({
      names: aiResult.attributes,
      candidates: QueryNodeDefs.getRawAttributeDefs({ survey, entityDef, cycle, includeAnalysis }),
      kind: 'attribute',
    })
    if (aiResult.attributes.length === 0) {
      errors.push('raw mode requires at least one attribute')
    }
    query = Query.assocAttributeDefUuids(attributeDefs.map(NodeDef.getUuid))(query)
    sortableDefs = attributeDefs
  }

  // filter
  if (StringUtils.isNotBlank(aiResult.filter)) {
    const filterAttributeDefs = QueryNodeDefs.getRawAttributeDefs({
      survey,
      entityDef,
      cycle,
      includeAnalysis,
    }).filter(NodeDef.isSingle)
    const allowedColumnNames = new Set<string>(filterAttributeDefs.flatMap(ColumnNodeDef.getColumnNames))
    const filterExpr = parseFilter({ filter: aiResult.filter, allowedColumnNames, errors })
    if (filterExpr) {
      query = Query.assocFilter(filterExpr)(query)
    }
  }

  // sort
  const sortOrders: string[] = Object.values(SortCriteria.orders)
  const sort = aiResult.sort.reduce((acc, { attribute, order }) => {
    const sortDef = sortableDefs.find((nodeDef) => NodeDef.getName(nodeDef) === attribute)
    if (!sortDef) {
      errors.push(
        `cannot sort by "${attribute}": sort attributes must be among the selected ${modeAggregate ? 'dimensions' : 'attributes'}`
      )
      return acc
    }
    // missing order means ascending; any other unexpected value is rejected (and fed back to the model)
    const orderNormalized = StringUtils.isBlank(order) ? SortCriteria.orders.asc : order.trim().toLowerCase()
    if (!sortOrders.includes(orderNormalized)) {
      errors.push(`invalid sort order "${order}" for "${attribute}"; allowed: ${sortOrders.join(', ')}`)
      return acc
    }
    const sortCriteria = SortCriteria.assocOrder(orderNormalized)(
      SortCriteria.assocVariable({
        variable: ColumnNodeDef.getColumnName(sortDef),
        label: NodeDef.getLabel(sortDef, lang),
      })(SortCriteria.create())
    )
    acc.push(sortCriteria)
    return acc
  }, [])
  query = Query.assocSort(sort)(query)

  if (errors.length > 0) {
    return { query: null, errors }
  }
  return { query, errors }
}

/**
 * Generates a Data Explorer query from a natural-language description.
 * @param {object} params - The parameters.
 * @param {object} params.user - Acting user.
 * @param {number} params.surveyId - Survey ID.
 * @param {string} params.cycle - Survey cycle key.
 * @param {string} params.lang - Language used for labels and for the explanation.
 * @param {string} params.description - The user's request in natural language.
 * @returns {Promise<{query: object, explanation: string}>} - The generated query and its explanation.
 */
export const generate = async ({
  user,
  surveyId,
  cycle,
  lang,
  description,
}: {
  user: any
  surveyId: number
  cycle: string
  lang: string
  description: string
}) => {
  if (StringUtils.isBlank(description)) {
    throw new SystemError('aiDataQueryDescriptionMissing')
  }
  if (description.length > MAX_DESCRIPTION_LEN) {
    throw new SystemError('aiInputTooLong', { field: 'description', limit: MAX_DESCRIPTION_LEN })
  }
  if (lang && String(lang).length > MAX_LANG_CODE_LEN) {
    throw new SystemError('aiInputTooLong', { field: 'lang', limit: MAX_LANG_CODE_LEN })
  }

  const survey = await SurveyManager.fetchSurveyAndNodeDefsBySurveyId({
    surveyId,
    cycle,
    draft: true,
    advanced: true,
  })
  const surveyInfo = Survey.getSurveyInfo(survey)
  const cycleKey = cycle ?? Survey.getDefaultCycleKey(surveyInfo)
  // analysis attributes are visible in the Data Explorer only to users who can analyze records
  const includeAnalysis = Authorizer.canAnalyzeRecords(user, surveyInfo)
  const langEffective =
    lang && (Survey.getLanguages(surveyInfo) as string[]).includes(lang) ? lang : Survey.getDefaultLanguage(surveyInfo)

  if (QueryNodeDefs.getQueryableEntityDefs({ survey, cycle: cycleKey }).length === 0) {
    throw new SystemError('aiDataQueryNoEntities')
  }

  const runOnce = async (previousError = null) => {
    const { system, prompt } = buildDataQueryGeneratePrompt({
      survey,
      cycle: cycleKey,
      lang: langEffective,
      description,
      includeAnalysis,
      previousError,
    })
    const { text } = await ModelClient.generate({ user, feature: 'dataQueryGenerate', system, prompt })
    let aiResult: AiResult
    try {
      aiResult = AiResultSchema.parse(parseJsonResponse(text))
    } catch (error) {
      return { aiResult: null, query: null, errors: [`invalid JSON answer: ${error?.message ?? error}`] }
    }
    const { query, errors } = toQuery({ survey, cycle: cycleKey, lang: langEffective, aiResult, includeAnalysis })
    return { aiResult, query, errors }
  }

  let result = await runOnce()
  if (result.errors.length > 0) {
    logger.info(`dataQueryGenerate validation failed on first try: ${result.errors.join('; ')}; retrying once`)
    result = await runOnce({ message: result.errors.join('; ') })
  }
  if (result.errors.length > 0) {
    throw new SystemError('aiDataQueryInvalid', { errors: result.errors.join('; ') })
  }
  const { aiResult, query } = result
  return { query, explanation: aiResult.explanation ?? '' }
}
