apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arena-rstudio-home
  labels:
    app.kubernetes.io/name: arena-rstudio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
