import * as R from 'ramda';

const languagesMap = {
  ab: {en: 'Abkhazian'},
  aa: {en: 'Afar'},
  af: {en: 'Afrikaans'},
  ak: {en: 'Akan'},
  sq: {en: 'Albanian'},
  am: {en: 'Amharic'},
  ar: {en: 'Arabic'},
  an: {en: 'Aragonese'},
  hy: {en: 'Armenian'},
  as: {en: 'Assamese'},
  av: {en: 'Avaric'},
  ae: {en: 'Avestan'},
  ay: {en: 'Aymara'},
  az: {en: 'Azerbaijani'},
  bm: {en: 'Bambara'},
  ba: {en: 'Bashkir'},
  eu: {en: 'Basque'},
  be: {en: 'Belarusian'},
  bn: {en: 'Bengali'},
  bh: {en: 'Bihari languages'},
  bi: {en: 'Bislama'},
  nb: {en: 'Bokmål, Norwegian; Norwegian Bokmål'},
  bs: {en: 'Bosnian'},
  br: {en: 'Breton'},
  bg: {en: 'Bulgarian'},
  my: {en: 'Burmese'},
  ca: {en: 'Catalan; Valencian'},
  km: {en: 'Central Khmer'},
  ch: {en: 'Chamorro'},
  ce: {en: 'Chechen'},
  ny: {en: 'Chichewa; Chewa; Nyanja'},
  zh: {en: 'Chinese'},
  cu: {en: 'Church Slavic; Church Slavonic'},
  cv: {en: 'Chuvash'},
  kw: {en: 'Cornish'},
  co: {en: 'Corsican'},
  cr: {en: 'Cree'},
  hr: {en: 'Croatian'},
  cs: {en: 'Czech'},
  da: {en: 'Danish'},
  dv: {en: 'Divehi; Dhivehi; Maldivian'},
  nl: {en: 'Dutch; Flemish'},
  dz: {en: 'Dzongkha'},
  en: {en: 'English'},
  eo: {en: 'Esperanto'},
  et: {en: 'Estonian'},
  ee: {en: 'Ewe'},
  fo: {en: 'Faroese'},
  fj: {en: 'Fijian'},
  fi: {en: 'Finnish'},
  fr: {en: 'French'},
  ff: {en: 'Fulah'},
  gd: {en: 'Gaelic; Scottish Gaelic'},
  gl: {en: 'Galician'},
  lg: {en: 'Ganda'},
  ka: {en: 'Georgian'},
  de: {en: 'German'},
  el: {en: 'Greek, Modern (1453-)'},
  gn: {en: 'Guarani'},
  gu: {en: 'Gujarati'},
  ht: {en: 'Haitian; Haitian Creole'},
  ha: {en: 'Hausa'},
  he: {en: 'Hebrew'},
  hz: {en: 'Herero'},
  hi: {en: 'Hindi'},
  ho: {en: 'Hiri Motu'},
  hu: {en: 'Hungarian'},
  is: {en: 'Icelandic'},
  io: {en: 'Ido'},
  ig: {en: 'Igbo'},
  id: {en: 'Indonesian'},
  ia: {en: 'Interlingua (International Auxiliary Language Association)'},
  ie: {en: 'Interlingue; Occidental'},
  iu: {en: 'Inuktitut'},
  ik: {en: 'Inupiaq'},
  ga: {en: 'Irish'},
  it: {en: 'Italian'},
  ja: {en: 'Japanese'},
  jv: {en: 'Javanese'},
  kl: {en: 'Kalaallisut; Greenlandic'},
  kn: {en: 'Kannada'},
  kr: {en: 'Kanuri'},
  ks: {en: 'Kashmiri'},
  kk: {en: 'Kazakh'},
  ki: {en: 'Kikuyu; Gikuyu'},
  rw: {en: 'Kinyarwanda'},
  ky: {en: 'Kirghiz; Kyrgyz'},
  kv: {en: 'Komi'},
  kg: {en: 'Kongo'},
  ko: {en: 'Korean'},
  kj: {en: 'Kuanyama; Kwanyama'},
  ku: {en: 'Kurdish'},
  lo: {en: 'Lao'},
  la: {en: 'Latin'},
  lv: {en: 'Latvian'},
  li: {en: 'Limburgan; Limburger; Limburgish'},
  ln: {en: 'Lingala'},
  lt: {en: 'Lithuanian'},
  lu: {en: 'Luba-Katanga'},
  lb: {en: 'Luxembourgish; Letzeburgesch'},
  mk: {en: 'Macedonian'},
  mg: {en: 'Malagasy'},
  ms: {en: 'Malay'},
  ml: {en: 'Malayalam'},
  mt: {en: 'Maltese'},
  gv: {en: 'Manx'},
  mi: {en: 'Maori'},
  mr: {en: 'Marathi'},
  mh: {en: 'Marshallese'},
  mn: {en: 'Mongolian'},
  na: {en: 'Nauru'},
  nv: {en: 'Navajo; Navaho'},
  nd: {en: 'Ndebele, North; North Ndebele'},
  nr: {en: 'Ndebele, South; South Ndebele'},
  ng: {en: 'Ndonga'},
  ne: {en: 'Nepali'},
  se: {en: 'Northern Sami'},
  no: {en: 'Norwegian'},
  nn: {en: 'Norwegian Nynorsk; Nynorsk, Norwegian'},
  oc: {en: 'Occitan (post 1500); Provençal'},
  oj: {en: 'Ojibwa'},
  or: {en: 'Oriya'},
  om: {en: 'Oromo'},
  os: {en: 'Ossetian; Ossetic'},
  pi: {en: 'Pali'},
  pa: {en: 'Panjabi; Punjabi'},
  fa: {en: 'Persian'},
  pl: {en: 'Polish'},
  pt: {en: 'Portuguese'},
  ps: {en: 'Pushto; Pashto'},
  qu: {en: 'Quechua'},
  ro: {en: 'Romanian; Moldavian; Moldovan'},
  rm: {en: 'Romansh'},
  rn: {en: 'Rundi'},
  ru: {en: 'Russian'},
  sm: {en: 'Samoan'},
  sg: {en: 'Sango'},
  sa: {en: 'Sanskrit'},
  sc: {en: 'Sardinian'},
  sr: {en: 'Serbian'},
  sn: {en: 'Shona'},
  ii: {en: 'Sichuan Yi; Nuosu'},
  sd: {en: 'Sindhi'},
  si: {en: 'Sinhala; Sinhalese'},
  sk: {en: 'Slovak'},
  sl: {en: 'Slovenian'},
  so: {en: 'Somali'},
  st: {en: 'Sotho, Southern'},
  es: {en: 'Spanish; Castilian'},
  su: {en: 'Sundanese'},
  sw: {en: 'Swahili'},
  ss: {en: 'Swati'},
  sv: {en: 'Swedish'},
  tl: {en: 'Tagalog'},
  ty: {en: 'Tahitian'},
  tg: {en: 'Tajik'},
  ta: {en: 'Tamil'},
  tt: {en: 'Tatar'},
  te: {en: 'Telugu'},
  th: {en: 'Thai'},
  bo: {en: 'Tibetan'},
  ti: {en: 'Tigrinya'},
  to: {en: 'Tonga (Tonga Islands)'},
  ts: {en: 'Tsonga'},
  tn: {en: 'Tswana'},
  tr: {en: 'Turkish'},
  tk: {en: 'Turkmen'},
  tw: {en: 'Twi'},
  ug: {en: 'Uighur; Uyghur'},
  uk: {en: 'Ukrainian'},
  ur: {en: 'Urdu'},
  uz: {en: 'Uzbek'},
  ve: {en: 'Venda'},
  vi: {en: 'Vietnamese'},
  vo: {en: 'Volapük'},
  wa: {en: 'Walloon'},
  cy: {en: 'Welsh'},
  fy: {en: 'Western Frisian'},
  wo: {en: 'Wolof'},
  xh: {en: 'Xhosa'},
  yi: {en: 'Yiddish'},
  yo: {en: 'Yoruba'},
  za: {en: 'Zhuang; Chuang'},
  zu: {en: 'Zulu'}
}

const language_ISO_636_2_Map = {
  aar: {en: 'Afar'},
  abk: {en: 'Abkhazian'},
  ace: {en: 'Achinese'},
  ach: {en: 'Acoli'},
  ada: {en: 'Adangme'},
  ady: {en: 'Adyghe; Adygei'},
  afa: {en: 'Afro-Asiatic languages'},
  afh: {en: 'Afrihili'},
  afr: {en: 'Afrikaans'},
  ain: {en: 'Ainu'},
  aka: {en: 'Akan'},
  akk: {en: 'Akkadian'},
  alb: {en: 'Albanian'},
  ale: {en: 'Aleut'},
  alg: {en: 'Algonquian languages'},
  alt: {en: 'Southern Altai'},
  amh: {en: 'Amharic'},
  ang: {en: 'English, Old (ca.450-1100)'},
  anp: {en: 'Angika'},
  apa: {en: 'Apache languages'},
  ara: {en: 'Arabic'},
  arc: {en: 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'},
  arg: {en: 'Aragonese'},
  arm: {en: 'Armenian'},
  arn: {en: 'Mapudungun; Mapuche'},
  arp: {en: 'Arapaho'},
  art: {en: 'Artificial languages'},
  arw: {en: 'Arawak'},
  asm: {en: 'Assamese'},
  ast: {en: 'Asturian; Bable; Leonese; Asturleonese'},
  ath: {en: 'Athapascan languages'},
  aus: {en: 'Australian languages'},
  ava: {en: 'Avaric'},
  ave: {en: 'Avestan'},
  awa: {en: 'Awadhi'},
  aym: {en: 'Aymara'},
  aze: {en: 'Azerbaijani'},
  bad: {en: 'Banda languages'},
  bai: {en: 'Bamileke languages'},
  bak: {en: 'Bashkir'},
  bal: {en: 'Baluchi'},
  bam: {en: 'Bambara'},
  ban: {en: 'Balinese'},
  baq: {en: 'Basque'},
  bas: {en: 'Basa'},
  bat: {en: 'Baltic languages'},
  bej: {en: 'Beja; Bedawiyet'},
  bel: {en: 'Belarusian'},
  bem: {en: 'Bemba'},
  ben: {en: 'Bengali'},
  ber: {en: 'Berber languages'},
  bho: {en: 'Bhojpuri'},
  bih: {en: 'Bihari languages'},
  bik: {en: 'Bikol'},
  bin: {en: 'Bini; Edo'},
  bis: {en: 'Bislama'},
  bla: {en: 'Siksika'},
  bnt: {en: 'Bantu languages'},
  bod: {en: 'Tibetan (T)'},
  bos: {en: 'Bosnian'},
  bra: {en: 'Braj'},
  bre: {en: 'Breton'},
  btk: {en: 'Batak languages'},
  bua: {en: 'Buriat'},
  bug: {en: 'Buginese'},
  bul: {en: 'Bulgarian'},
  bur: {en: 'Burmese'},
  byn: {en: 'Blin; Bilin'},
  cad: {en: 'Caddo'},
  cai: {en: 'Central American Indian languages'},
  car: {en: 'Galibi Carib'},
  cat: {en: 'Catalan; Valencian'},
  cau: {en: 'Caucasian languages'},
  ceb: {en: 'Cebuano'},
  cel: {en: 'Celtic languages'},
  ces: {en: 'Czech (T)'},
  cha: {en: 'Chamorro'},
  chb: {en: 'Chibcha'},
  che: {en: 'Chechen'},
  chg: {en: 'Chagatai'},
  chi: {en: 'Chinese'},
  chk: {en: 'Chuukese'},
  chm: {en: 'Mari'},
  chn: {en: 'Chinook jargon'},
  cho: {en: 'Choctaw'},
  chp: {en: 'Chipewyan; Dene Suline'},
  chr: {en: 'Cherokee'},
  chu: {en: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'},
  chv: {en: 'Chuvash'},
  chy: {en: 'Cheyenne'},
  cmc: {en: 'Chamic languages'},
  cnr: {en: 'Montenegrin'},
  cop: {en: 'Coptic'},
  cor: {en: 'Cornish'},
  cos: {en: 'Corsican'},
  cpe: {en: 'Creoles and pidgins, English based'},
  cpf: {en: 'Creoles and pidgins, French-based'},
  cpp: {en: 'Creoles and pidgins, Portuguese-based'},
  cre: {en: 'Cree'},
  crh: {en: 'Crimean Tatar; Crimean Turkish'},
  crp: {en: 'Creoles and pidgins'},
  csb: {en: 'Kashubian'},
  cus: {en: 'Cushitic languages'},
  cym: {en: 'Welsh (T)'},
  cze: {en: 'Czech'},
  dak: {en: 'Dakota'},
  dan: {en: 'Danish'},
  dar: {en: 'Dargwa'},
  day: {en: 'Land Dayak languages'},
  del: {en: 'Delaware'},
  den: {en: 'Slave (Athapascan)'},
  deu: {en: 'German (T)'},
  dgr: {en: 'Dogrib'},
  din: {en: 'Dinka'},
  div: {en: 'Divehi; Dhivehi; Maldivian'},
  doi: {en: 'Dogri'},
  dra: {en: 'Dravidian languages'},
  dsb: {en: 'Lower Sorbian'},
  dua: {en: 'Duala'},
  dum: {en: 'Dutch, Middle (ca.1050-1350)'},
  dut: {en: 'Dutch; Flemish'},
  dyu: {en: 'Dyula'},
  dzo: {en: 'Dzongkha'},
  efi: {en: 'Efik'},
  egy: {en: 'Egyptian (Ancient)'},
  eka: {en: 'Ekajuk'},
  ell: {en: 'Greek, Modern (1453-) (T)'},
  elx: {en: 'Elamite'},
  eng: {en: 'English'},
  enm: {en: 'English, Middle (1100-1500)'},
  epo: {en: 'Esperanto'},
  est: {en: 'Estonian'},
  eus: {en: 'Basque (T)'},
  ewe: {en: 'Ewe'},
  ewo: {en: 'Ewondo'},
  fan: {en: 'Fang'},
  fao: {en: 'Faroese'},
  fas: {en: 'Persian (T)'},
  fat: {en: 'Fanti'},
  fij: {en: 'Fijian'},
  fil: {en: 'Filipino; Pilipino'},
  fin: {en: 'Finnish'},
  fiu: {en: 'Finno-Ugrian languages'},
  fon: {en: 'Fon'},
  fra: {en: 'French (T)'},
  fre: {en: 'French (B)'},
  frm: {en: 'French, Middle (ca.1400-1600)'},
  fro: {en: 'French, Old (842-ca.1400)'},
  frr: {en: 'Northern Frisian'},
  frs: {en: 'Eastern Frisian'},
  fry: {en: 'Western Frisian'},
  ful: {en: 'Fulah'},
  fur: {en: 'Friulian'},
  gaa: {en: 'Ga'},
  gay: {en: 'Gayo'},
  gba: {en: 'Gbaya'},
  gem: {en: 'Germanic languages'},
  geo: {en: 'Georgian'},
  ger: {en: 'German'},
  gez: {en: 'Geez'},
  gil: {en: 'Gilbertese'},
  gla: {en: 'Gaelic; Scottish Gaelic'},
  gle: {en: 'Irish'},
  glg: {en: 'Galician'},
  glv: {en: 'Manx'},
  gmh: {en: 'German, Middle High (ca.1050-1500)'},
  goh: {en: 'German, Old High (ca.750-1050)'},
  gon: {en: 'Gondi'},
  gor: {en: 'Gorontalo'},
  got: {en: 'Gothic'},
  grb: {en: 'Grebo'},
  grc: {en: 'Greek, Ancient (to 1453)'},
  gre: {en: 'Greek, Modern (1453-)'},
  grn: {en: 'Guarani'},
  gsw: {en: 'Swiss German; Alemannic; Alsatian'},
  guj: {en: 'Gujarati'},
  gwi: {en: 'Gwich\'in'},
  hai: {en: 'Haida'},
  hat: {en: 'Haitian; Haitian Creole'},
  hau: {en: 'Hausa'},
  haw: {en: 'Hawaiian'},
  heb: {en: 'Hebrew'},
  her: {en: 'Herero'},
  hil: {en: 'Hiligaynon'},
  him: {en: 'Himachali languages; Western Pahari languages'},
  hin: {en: 'Hindi'},
  hit: {en: 'Hittite'},
  hmn: {en: 'Hmong; Mong'},
  hmo: {en: 'Hiri Motu'},
  hrv: {en: 'Croatian'},
  hsb: {en: 'Upper Sorbian'},
  hun: {en: 'Hungarian'},
  hup: {en: 'Hupa'},
  hye: {en: 'Armenian (T)'},
  iba: {en: 'Iban'},
  ibo: {en: 'Igbo'},
  ice: {en: 'Icelandic'},
  ido: {en: 'Ido'},
  iii: {en: 'Sichuan Yi; Nuosu'},
  ijo: {en: 'Ijo languages'},
  iku: {en: 'Inuktitut'},
  ile: {en: 'Interlingue; Occidental'},
  ilo: {en: 'Iloko'},
  ina: {en: 'Interlingua (International Auxiliary Language Association)'},
  inc: {en: 'Indic languages'},
  ind: {en: 'Indonesian'},
  ine: {en: 'Indo-European languages'},
  inh: {en: 'Ingush'},
  ipk: {en: 'Inupiaq'},
  ira: {en: 'Iranian languages'},
  iro: {en: 'Iroquoian languages'},
  isl: {en: 'Icelandic (T)'},
  ita: {en: 'Italian'},
  jav: {en: 'Javanese'},
  jbo: {en: 'Lojban'},
  jpn: {en: 'Japanese'},
  jpr: {en: 'Judeo-Persian'},
  jrb: {en: 'Judeo-Arabic'},
  kaa: {en: 'Kara-Kalpak'},
  kab: {en: 'Kabyle'},
  kac: {en: 'Kachin; Jingpho'},
  kal: {en: 'Kalaallisut; Greenlandic'},
  kam: {en: 'Kamba'},
  kan: {en: 'Kannada'},
  kar: {en: 'Karen languages'},
  kas: {en: 'Kashmiri'},
  kat: {en: 'Georgian (T)'},
  kau: {en: 'Kanuri'},
  kaw: {en: 'Kawi'},
  kaz: {en: 'Kazakh'},
  kbd: {en: 'Kabardian'},
  kha: {en: 'Khasi'},
  khi: {en: 'Khoisan languages'},
  khm: {en: 'Central Khmer'},
  kho: {en: 'Khotanese; Sakan'},
  kik: {en: 'Kikuyu; Gikuyu'},
  kin: {en: 'Kinyarwanda'},
  kir: {en: 'Kirghiz; Kyrgyz'},
  kmb: {en: 'Kimbundu'},
  kok: {en: 'Konkani'},
  kom: {en: 'Komi'},
  kon: {en: 'Kongo'},
  kor: {en: 'Korean'},
  kos: {en: 'Kosraean'},
  kpe: {en: 'Kpelle'},
  krc: {en: 'Karachay-Balkar'},
  krl: {en: 'Karelian'},
  kro: {en: 'Kru languages'},
  kru: {en: 'Kurukh'},
  kua: {en: 'Kuanyama; Kwanyama'},
  kum: {en: 'Kumyk'},
  kur: {en: 'Kurdish'},
  kut: {en: 'Kutenai'},
  lad: {en: 'Ladino'},
  lah: {en: 'Lahnda'},
  lam: {en: 'Lamba'},
  lao: {en: 'Lao'},
  lat: {en: 'Latin'},
  lav: {en: 'Latvian'},
  lez: {en: 'Lezghian'},
  lim: {en: 'Limburgan; Limburger; Limburgish'},
  lin: {en: 'Lingala'},
  lit: {en: 'Lithuanian'},
  lol: {en: 'Mongo'},
  loz: {en: 'Lozi'},
  ltz: {en: 'Luxembourgish; Letzeburgesch'},
  lua: {en: 'Luba-Lulua'},
  lub: {en: 'Luba-Katanga'},
  lug: {en: 'Ganda'},
  lui: {en: 'Luiseno'},
  lun: {en: 'Lunda'},
  luo: {en: 'Luo (Kenya and Tanzania)'},
  lus: {en: 'Lushai'},
  mac: {en: 'Macedonian'},
  mad: {en: 'Madurese'},
  mag: {en: 'Magahi'},
  mah: {en: 'Marshallese'},
  mai: {en: 'Maithili'},
  mak: {en: 'Makasar'},
  mal: {en: 'Malayalam'},
  man: {en: 'Mandingo'},
  mao: {en: 'Maori'},
  map: {en: 'Austronesian languages'},
  mar: {en: 'Marathi'},
  mas: {en: 'Masai'},
  may: {en: 'Malay'},
  mdf: {en: 'Moksha'},
  mdr: {en: 'Mandar'},
  men: {en: 'Mende'},
  mga: {en: 'Irish, Middle (900-1200)'},
  mic: {en: 'Mi\'kmaq; Micmac'},
  min: {en: 'Minangkabau'},
  mis: {en: 'Uncoded languages'},
  mkd: {en: 'Macedonian (T)'},
  mkh: {en: 'Mon-Khmer languages'},
  mlg: {en: 'Malagasy'},
  mlt: {en: 'Maltese'},
  mnc: {en: 'Manchu'},
  mni: {en: 'Manipuri'},
  mno: {en: 'Manobo languages'},
  moh: {en: 'Mohawk'},
  mon: {en: 'Mongolian'},
  mos: {en: 'Mossi'},
  mri: {en: 'Maori (T)'},
  msa: {en: 'Malay (T)'},
  mul: {en: 'Multiple languages'},
  mun: {en: 'Munda languages'},
  mus: {en: 'Creek'},
  mwl: {en: 'Mirandese'},
  mwr: {en: 'Marwari'},
  mya: {en: 'Burmese (T)'},
  myn: {en: 'Mayan languages'},
  myv: {en: 'Erzya'},
  nah: {en: 'Nahuatl languages'},
  nai: {en: 'North American Indian languages'},
  nap: {en: 'Neapolitan'},
  nau: {en: 'Nauru'},
  nav: {en: 'Navajo; Navaho'},
  nbl: {en: 'Ndebele, South; South Ndebele'},
  nde: {en: 'Ndebele, North; North Ndebele'},
  ndo: {en: 'Ndonga'},
  nds: {en: 'Low German; Low Saxon; German, Low; Saxon, Low'},
  nep: {en: 'Nepali'},
  new: {en: 'Nepal Bhasa; Newari'},
  nia: {en: 'Nias'},
  nic: {en: 'Niger-Kordofanian languages'},
  niu: {en: 'Niuean'},
  nld: {en: 'Dutch; Flemish (T)'},
  nno: {en: 'Norwegian Nynorsk; Nynorsk, Norwegian'},
  nob: {en: 'Bokmål, Norwegian; Norwegian Bokmål'},
  nog: {en: 'Nogai'},
  non: {en: 'Norse, Old'},
  nor: {en: 'Norwegian'},
  nqo: {en: 'N\'Ko'},
  nso: {en: 'Pedi; Sepedi; Northern Sotho'},
  nub: {en: 'Nubian languages'},
  nwc: {en: 'Classical Newari; Old Newari; Classical Nepal Bhasa'},
  nya: {en: 'Chichewa; Chewa; Nyanja'},
  nym: {en: 'Nyamwezi'},
  nyn: {en: 'Nyankole'},
  nyo: {en: 'Nyoro'},
  nzi: {en: 'Nzima'},
  oci: {en: 'Occitan (post 1500)'},
  oji: {en: 'Ojibwa'},
  ori: {en: 'Oriya'},
  orm: {en: 'Oromo'},
  osa: {en: 'Osage'},
  oss: {en: 'Ossetian; Ossetic'},
  ota: {en: 'Turkish, Ottoman (1500-1928)'},
  oto: {en: 'Otomian languages'},
  paa: {en: 'Papuan languages'},
  pag: {en: 'Pangasinan'},
  pal: {en: 'Pahlavi'},
  pam: {en: 'Pampanga; Kapampangan'},
  pan: {en: 'Panjabi; Punjabi'},
  pap: {en: 'Papiamento'},
  pau: {en: 'Palauan'},
  peo: {en: 'Persian, Old (ca.600-400 B.C.)'},
  per: {en: 'Persian'},
  phi: {en: 'Philippine languages'},
  phn: {en: 'Phoenician'},
  pli: {en: 'Pali'},
  pol: {en: 'Polish'},
  pon: {en: 'Pohnpeian'},
  por: {en: 'Portuguese'},
  pra: {en: 'Prakrit languages'},
  pro: {en: 'Provençal, Old (to 1500);Occitan, Old (to 1500)'},
  pus: {en: 'Pushto; Pashto'},
  que: {en: 'Quechua'},
  raj: {en: 'Rajasthani'},
  rap: {en: 'Rapanui'},
  rar: {en: 'Rarotongan; Cook Islands Maori'},
  roa: {en: 'Romance languages'},
  roh: {en: 'Romansh'},
  rom: {en: 'Romany'},
  ron: {en: 'Romanian; Moldavian; Moldovan (T)'},
  rum: {en: 'Romanian; Moldavian; Moldovan'},
  run: {en: 'Rundi'},
  rup: {en: 'Aromanian; Arumanian; Macedo-Romanian'},
  rus: {en: 'Russian'},
  sad: {en: 'Sandawe'},
  sag: {en: 'Sango'},
  sah: {en: 'Yakut'},
  sai: {en: 'South American Indian languages'},
  sal: {en: 'Salishan languages'},
  sam: {en: 'Samaritan Aramaic'},
  san: {en: 'Sanskrit'},
  sas: {en: 'Sasak'},
  sat: {en: 'Santali'},
  scn: {en: 'Sicilian'},
  sco: {en: 'Scots'},
  sel: {en: 'Selkup'},
  sem: {en: 'Semitic languages'},
  sga: {en: 'Irish, Old (to 900)'},
  sgn: {en: 'Sign Languages'},
  shn: {en: 'Shan'},
  sid: {en: 'Sidamo'},
  sin: {en: 'Sinhala; Sinhalese'},
  sio: {en: 'Siouan languages'},
  sit: {en: 'Sino-Tibetan languages'},
  sla: {en: 'Slavic languages'},
  slk: {en: 'Slovak (T)'},
  slo: {en: 'Slovak'},
  slv: {en: 'Slovenian'},
  sma: {en: 'Southern Sami'},
  sme: {en: 'Northern Sami'},
  smi: {en: 'Sami languages'},
  smj: {en: 'Lule Sami'},
  smn: {en: 'Inari Sami'},
  smo: {en: 'Samoan'},
  sms: {en: 'Skolt Sami'},
  sna: {en: 'Shona'},
  snd: {en: 'Sindhi'},
  snk: {en: 'Soninke'},
  sog: {en: 'Sogdian'},
  som: {en: 'Somali'},
  son: {en: 'Songhai languages'},
  sot: {en: 'Sotho, Southern'},
  spa: {en: 'Spanish; Castilian'},
  sqi: {en: 'Albanian (T)'},
  srd: {en: 'Sardinian'},
  srn: {en: 'Sranan Tongo'},
  srp: {en: 'Serbian'},
  srr: {en: 'Serer'},
  ssa: {en: 'Nilo-Saharan languages'},
  ssw: {en: 'Swati'},
  suk: {en: 'Sukuma'},
  sun: {en: 'Sundanese'},
  sus: {en: 'Susu'},
  sux: {en: 'Sumerian'},
  swa: {en: 'Swahili'},
  swe: {en: 'Swedish'},
  syc: {en: 'Classical Syriac'},
  syr: {en: 'Syriac'},
  tah: {en: 'Tahitian'},
  tai: {en: 'Tai languages'},
  tam: {en: 'Tamil'},
  tat: {en: 'Tatar'},
  tel: {en: 'Telugu'},
  tem: {en: 'Timne'},
  ter: {en: 'Tereno'},
  tet: {en: 'Tetum'},
  tgk: {en: 'Tajik'},
  tgl: {en: 'Tagalog'},
  tha: {en: 'Thai'},
  tib: {en: 'Tibetan'},
  tig: {en: 'Tigre'},
  tir: {en: 'Tigrinya'},
  tiv: {en: 'Tiv'},
  tkl: {en: 'Tokelau'},
  tlh: {en: 'Klingon; tlhIngan-Hol'},
  tli: {en: 'Tlingit'},
  tmh: {en: 'Tamashek'},
  tog: {en: 'Tonga (Nyasa)'},
  ton: {en: 'Tonga (Tonga Islands)'},
  tpi: {en: 'Tok Pisin'},
  tsi: {en: 'Tsimshian'},
  tsn: {en: 'Tswana'},
  tso: {en: 'Tsonga'},
  tuk: {en: 'Turkmen'},
  tum: {en: 'Tumbuka'},
  tup: {en: 'Tupi languages'},
  tur: {en: 'Turkish'},
  tut: {en: 'Altaic languages'},
  tvl: {en: 'Tuvalu'},
  twi: {en: 'Twi'},
  tyv: {en: 'Tuvinian'},
  udm: {en: 'Udmurt'},
  uga: {en: 'Ugaritic'},
  uig: {en: 'Uighur; Uyghur'},
  ukr: {en: 'Ukrainian'},
  umb: {en: 'Umbundu'},
  und: {en: 'Undetermined'},
  urd: {en: 'Urdu'},
  uzb: {en: 'Uzbek'},
  vai: {en: 'Vai'},
  ven: {en: 'Venda'},
  vie: {en: 'Vietnamese'},
  vol: {en: 'Volapük'},
  vot: {en: 'Votic'},
  wak: {en: 'Wakashan languages'},
  wal: {en: 'Wolaitta; Wolaytta'},
  war: {en: 'Waray'},
  was: {en: 'Washo'},
  wel: {en: 'Welsh'},
  wen: {en: 'Sorbian languages'},
  wln: {en: 'Walloon'},
  wol: {en: 'Wolof'},
  xal: {en: 'Kalmyk; Oirat'},
  xho: {en: 'Xhosa'},
  yao: {en: 'Yao'},
  yap: {en: 'Yapese'},
  yid: {en: 'Yiddish'},
  yor: {en: 'Yoruba'},
  ypk: {en: 'Yupik languages'},
  zap: {en: 'Zapotec'},
  zbl: {en: 'Blissymbols; Blissymbolics; Bliss'},
  zen: {en: 'Zenaga'},
  zgh: {en: 'Standard Moroccan Tamazight'},
  zha: {en: 'Zhuang; Chuang'},
  zho: {en: 'Chinese (T)'},
  znd: {en: 'Zande languages'},
  zul: {en: 'Zulu'},
  zun: {en: 'Zuni'},
  zxx: {en: 'No linguistic content; Not applicable'},
  zza: {en: 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'},
}

export const getLanguageLabel: (lang: string, translationLang?: string) => string
= (lang, translationLang = 'en') => R.path([lang, translationLang], languagesMap)

export const languages = R.pipe(
  R.keys,
  R.map(lang => ({key: lang, value: getLanguageLabel(lang)}))
)(languagesMap)

export const languageCodes = languages.map(R.prop('key'))

export const languageCodesISO636_2 = R.keys(language_ISO_636_2_Map)

export default {
  languages,
  languageCodes,
  languageCodesISO636_2,

  getLanguageLabel,
};
