import * as R from 'ramda'

const languagesMap = {
  ab: {en: 'Abkhazian'},
  aa: {en: 'Afar'},
  af: {en: 'Afrikaans'},
  ak: {en: 'Akan'},
  sq: {en: 'Albanian'},
  am: {en: 'Amharic'},
  ar: {en: 'Arabic'},
  an: {en: 'Aragonese'},
  hy: {en: 'Armenian'},
  as: {en: 'Assamese'},
  av: {en: 'Avaric'},
  ae: {en: 'Avestan'},
  ay: {en: 'Aymara'},
  az: {en: 'Azerbaijani'},
  bm: {en: 'Bambara'},
  ba: {en: 'Bashkir'},
  eu: {en: 'Basque'},
  be: {en: 'Belarusian'},
  bn: {en: 'Bengali'},
  bh: {en: 'Bihari languages'},
  bi: {en: 'Bislama'},
  nb: {en: 'Bokmål, Norwegian; Norwegian Bokmål'},
  bs: {en: 'Bosnian'},
  br: {en: 'Breton'},
  bg: {en: 'Bulgarian'},
  my: {en: 'Burmese'},
  ca: {en: 'Catalan; Valencian'},
  km: {en: 'Central Khmer'},
  ch: {en: 'Chamorro'},
  ce: {en: 'Chechen'},
  ny: {en: 'Chichewa; Chewa; Nyanja'},
  zh: {en: 'Chinese'},
  cu: {en: 'Church Slavic; Church Slavonic'},
  cv: {en: 'Chuvash'},
  kw: {en: 'Cornish'},
  co: {en: 'Corsican'},
  cr: {en: 'Cree'},
  hr: {en: 'Croatian'},
  cs: {en: 'Czech'},
  da: {en: 'Danish'},
  dv: {en: 'Divehi; Dhivehi; Maldivian'},
  nl: {en: 'Dutch; Flemish'},
  dz: {en: 'Dzongkha'},
  en: {en: 'English'},
  eo: {en: 'Esperanto'},
  et: {en: 'Estonian'},
  ee: {en: 'Ewe'},
  fo: {en: 'Faroese'},
  fj: {en: 'Fijian'},
  fi: {en: 'Finnish'},
  fr: {en: 'French'},
  ff: {en: 'Fulah'},
  gd: {en: 'Gaelic; Scottish Gaelic'},
  gl: {en: 'Galician'},
  lg: {en: 'Ganda'},
  ka: {en: 'Georgian'},
  de: {en: 'German'},
  el: {en: 'Greek, Modern (1453-)'},
  gn: {en: 'Guarani'},
  gu: {en: 'Gujarati'},
  ht: {en: 'Haitian; Haitian Creole'},
  ha: {en: 'Hausa'},
  he: {en: 'Hebrew'},
  hz: {en: 'Herero'},
  hi: {en: 'Hindi'},
  ho: {en: 'Hiri Motu'},
  hu: {en: 'Hungarian'},
  is: {en: 'Icelandic'},
  io: {en: 'Ido'},
  ig: {en: 'Igbo'},
  id: {en: 'Indonesian'},
  ia: {en: 'Interlingua (International Auxiliary Language Association)'},
  ie: {en: 'Interlingue; Occidental'},
  iu: {en: 'Inuktitut'},
  ik: {en: 'Inupiaq'},
  ga: {en: 'Irish'},
  it: {en: 'Italian'},
  ja: {en: 'Japanese'},
  jv: {en: 'Javanese'},
  kl: {en: 'Kalaallisut; Greenlandic'},
  kn: {en: 'Kannada'},
  kr: {en: 'Kanuri'},
  ks: {en: 'Kashmiri'},
  kk: {en: 'Kazakh'},
  ki: {en: 'Kikuyu; Gikuyu'},
  rw: {en: 'Kinyarwanda'},
  ky: {en: 'Kirghiz; Kyrgyz'},
  kv: {en: 'Komi'},
  kg: {en: 'Kongo'},
  ko: {en: 'Korean'},
  kj: {en: 'Kuanyama; Kwanyama'},
  ku: {en: 'Kurdish'},
  lo: {en: 'Lao'},
  la: {en: 'Latin'},
  lv: {en: 'Latvian'},
  li: {en: 'Limburgan; Limburger; Limburgish'},
  ln: {en: 'Lingala'},
  lt: {en: 'Lithuanian'},
  lu: {en: 'Luba-Katanga'},
  lb: {en: 'Luxembourgish; Letzeburgesch'},
  mk: {en: 'Macedonian'},
  mg: {en: 'Malagasy'},
  ms: {en: 'Malay'},
  ml: {en: 'Malayalam'},
  mt: {en: 'Maltese'},
  gv: {en: 'Manx'},
  mi: {en: 'Maori'},
  mr: {en: 'Marathi'},
  mh: {en: 'Marshallese'},
  mn: {en: 'Mongolian'},
  na: {en: 'Nauru'},
  nv: {en: 'Navajo; Navaho'},
  nd: {en: 'Ndebele, North; North Ndebele'},
  nr: {en: 'Ndebele, South; South Ndebele'},
  ng: {en: 'Ndonga'},
  ne: {en: 'Nepali'},
  se: {en: 'Northern Sami'},
  no: {en: 'Norwegian'},
  nn: {en: 'Norwegian Nynorsk; Nynorsk, Norwegian'},
  oc: {en: 'Occitan (post 1500); Provençal'},
  oj: {en: 'Ojibwa'},
  or: {en: 'Oriya'},
  om: {en: 'Oromo'},
  os: {en: 'Ossetian; Ossetic'},
  pi: {en: 'Pali'},
  pa: {en: 'Panjabi; Punjabi'},
  fa: {en: 'Persian'},
  pl: {en: 'Polish'},
  pt: {en: 'Portuguese'},
  ps: {en: 'Pushto; Pashto'},
  qu: {en: 'Quechua'},
  ro: {en: 'Romanian; Moldavian; Moldovan'},
  rm: {en: 'Romansh'},
  rn: {en: 'Rundi'},
  ru: {en: 'Russian'},
  sm: {en: 'Samoan'},
  sg: {en: 'Sango'},
  sa: {en: 'Sanskrit'},
  sc: {en: 'Sardinian'},
  sr: {en: 'Serbian'},
  sn: {en: 'Shona'},
  ii: {en: 'Sichuan Yi; Nuosu'},
  sd: {en: 'Sindhi'},
  si: {en: 'Sinhala; Sinhalese'},
  sk: {en: 'Slovak'},
  sl: {en: 'Slovenian'},
  so: {en: 'Somali'},
  st: {en: 'Sotho, Southern'},
  es: {en: 'Spanish; Castilian'},
  su: {en: 'Sundanese'},
  sw: {en: 'Swahili'},
  ss: {en: 'Swati'},
  sv: {en: 'Swedish'},
  tl: {en: 'Tagalog'},
  ty: {en: 'Tahitian'},
  tg: {en: 'Tajik'},
  ta: {en: 'Tamil'},
  tt: {en: 'Tatar'},
  te: {en: 'Telugu'},
  th: {en: 'Thai'},
  bo: {en: 'Tibetan'},
  ti: {en: 'Tigrinya'},
  to: {en: 'Tonga (Tonga Islands)'},
  ts: {en: 'Tsonga'},
  tn: {en: 'Tswana'},
  tr: {en: 'Turkish'},
  tk: {en: 'Turkmen'},
  tw: {en: 'Twi'},
  ug: {en: 'Uighur; Uyghur'},
  uk: {en: 'Ukrainian'},
  ur: {en: 'Urdu'},
  uz: {en: 'Uzbek'},
  ve: {en: 'Venda'},
  vi: {en: 'Vietnamese'},
  vo: {en: 'Volapük'},
  wa: {en: 'Walloon'},
  cy: {en: 'Welsh'},
  fy: {en: 'Western Frisian'},
  wo: {en: 'Wolof'},
  xh: {en: 'Xhosa'},
  yi: {en: 'Yiddish'},
  yo: {en: 'Yoruba'},
  za: {en: 'Zhuang; Chuang'},
  zu: {en: 'Zulu'}
}

const getLanguageLabel = (lang, translationLang = 'en') => R.path([lang, translationLang], languagesMap)

const languages = R.pipe(
  R.keys,
  R.map(lang => ({key: lang, value: getLanguageLabel(lang)}))
)(languagesMap)

module.exports = {
  languages,

  getLanguageLabel,
}
