@startuml
title Processing chain

participant Step1_TREE
participant Step2_TREE_VIRTUAL
participant Step3_PLOT
participant Step4_STRATUM
participant Step5_AOI

' Create virtual entity by filtering data using sql
Step1_TREE -> Step2_TREE_VIRTUAL : create_virtual_entity

' Calculate any quantitative or categorical variable
Step2_TREE_VIRTUAL -> Step2_TREE_VIRTUAL  : dbh_class
Step2_TREE_VIRTUAL -> Step2_TREE_VIRTUAL  : volume
Step2_TREE_VIRTUAL -> Step2_TREE_VIRTUAL : plot_area
Step2_TREE_VIRTUAL -> Step2_TREE_VIRTUAL  : volume_per_ha


' Aggregate any quantitative variable to a next step
' Calculate any quantitative or categorical variable
Step2_TREE_VIRTUAL -> Step3_PLOT  : volume_per_ha (sum)
Step3_PLOT -> Step3_PLOT : weight

' Aggregate any quantitative variable to a next step
' Calculate any quantitative or categorical variable
Step3_PLOT -> Step4_STRATUM : weight (sum)
Step4_STRATUM -> Step4_STRATUM : exp_factor ( A / weight (sum) )
Step3_PLOT -> Step4_STRATUM : volume_per_ha (exp_factor * volume_per_ha)

' Aggregate any quantitative variable to a next step
' Calculate any quantitative or categorical variable
Step4_STRATUM -> Step5_AOI : volume_per_ha (sum)

@enduml