@startuml
title Record View
hide footbox

actor User #red
participant UI
participant RecordApi
participant RecordService
participant RecordManager
participant RecordRepository
participant NodeRepository
participant ThreadManager
participant RecordUpdateThread

User -> UI : Open RecordView

    UI -> UI : load blank page

    UI --> RecordApi ++ : **""POST""** check-in record
        RecordApi -> RecordService ++ : checkIn

            RecordService -> RecordManager ++ : fetchRecordAndNodesByUuid
                RecordManager -> RecordRepository ++ : fetchRecord
                    RecordRepository -> RecordManager -- : record
                RecordManager -> NodeRepository ++ : fetchNodesByRecordUuid
                    NodeRepository -> RecordManager -- : nodes
                RecordManager -> RecordService --: record

            RecordService -> ThreadManager ++ : createRecordUpdateThread
                ThreadManager -> RecordUpdateThread ++ : create thread
                    RecordUpdateThread -> ThreadManager: thread created
                ThreadManager -> RecordService -- : RecordUpdateThread instance

            RecordService -> RecordService: put thread into cache
            RecordService -> RecordApi -- : record

        RecordApi --> UI -- : record
    UI -> UI : Load form with record

||100||

User -> UI: Update node
    UI -> UI : Update UI state with user changes

    UI --> RecordApi: **""POST""** node update
        RecordApi --> RecordService ++ : persistNode
            RecordService -> RecordService: get thread from cache
                RecordService --> RecordUpdateThread: postMessage
            return ok
        return ok

||100||

User -> UI : Close RecordView
    UI --> RecordApi ++ : **""POST""** checkOut record
        RecordApi -> RecordService ++ : checkOut
            RecordService -> RecordUpdateThread !! : terminate
            return
        return
@enduml
