@startuml

entity Caller
participant RecordValidator
participant AttributeValidator
participant AttributeTypeValidator
participant EntityUniquenessValidator
participant CountValidator

box "Record" #ece8d6
participant Record
participant RecordExpressionParser
end box

Caller -> RecordValidator ++ : validateNodes

'1
RecordValidator -> AttributeValidator ++ : validateSelfAndDependentAttributes
    loop N = attributes
        AttributeValidator -> Record ++ : getDependentNodes
            Record -> AttributeValidator -- : dependents
            loop N = attributeAndDependents
                AttributeValidator -> AttributeValidator ++ #FFCFCF : validateAttribute
                    AttributeValidator -> AttributeValidator ++ #FF6F6F: validateRequired
                        AttributeValidator -> AttributeValidator -- : validation

                    AttributeValidator -> AttributeTypeValidator ++ : validateValueType
                        AttributeTypeValidator -> AttributeValidator -- : validation

                    AttributeValidator -> AttributeValidator ++ #FF6F6F : validateNodeValidations
                        AttributeValidator -> RecordExpressionParser ++ : evalApplicableExpressions
                            RecordExpressionParser -> AttributeValidator -- : expressionsEvaluated
                        AttributeValidator -> AttributeValidator -- : validations

                    AttributeValidator -> AttributeValidator -- : attributeValidations
            end
    end
    AttributeValidator -> RecordValidator -- : attributeValidations

'2 CountValidator
RecordValidator -> CountValidator ++ : validateChildrenCount
    CountValidator -> RecordValidator  -- : validation
'3
RecordValidator -> EntityUniquenessValidator ++ #FFCFCF : validateEntityKeysUniqueness
    EntityUniquenessValidator -> EntityUniquenessValidator ++ #FF6F6F : getUpdatedEntitiesWithKeys
        EntityUniquenessValidator -> EntityUniquenessValidator -- : entities
        loop N = entities
            EntityUniquenessValidator -> EntityUniquenessValidator ++ #FF6F6F : validateEntityKeysUniqueness
                EntityUniquenessValidator -> EntityUniquenessValidator -- : validations
        end
        EntityUniquenessValidator -> RecordValidator -- : validations
    RecordValidator -> RecordValidator -- : validations

RecordValidator -> Caller -- : validations
@enduml