export default {
  authenticatorCodeOne: 'Authenticator code 1',
  authenticatorCodeTwo: 'Authenticator code 2',
  create: {
    label: 'Create',
  },
  deletion: {
    confirm: 'Are you sure you want to delete the device "{{deviceName}}"?',
    error: 'Error deleting device: {{message}}',
    successful: 'Device deleted successfully',
  },
  deviceName: 'Device name',
  enabled: 'Enabled',
  error: {
    fetchDevice: 'Error fetching device details: {{message}}',
    createDevice: 'Error creating device: {{message}}',
    updateDevice: 'Error updating device: {{message}}',
  },
  showSecretKey: 'Show secret key',
  validation: {
    label: 'Validate',
    successful: 'Device validated successfully',
    error: 'Invalid authenticator codes',
  },
  validationSteps: {
    installAuthenticatorApp: {
      title: 'Install Authenticator App',
      description: 'Install an authenticator app on your mobile device (e.g. Google Authenticator, Authy, etc.).',
    },
    scanCode: {
      title: 'Scan QR Code',
      description: 'Use the authenticator app to scan the QR code.',
    },
    typeAuthenticatorCodes: {
      title: 'Type Authenticator Codes',
      description: 'Enter the codes generated by the authenticator app.',
    },
  },
}
