import { FileFormats } from '@core/fileFormats'
import * as Survey from '@core/survey/survey'
import * as Category from '@core/survey/category'
import * as CategoryImportSummary from '@core/survey/categoryImportSummary'
import { ExtraPropDef } from '@core/survey/extraPropDef'

import * as CategoryManager from '@server/modules/category/manager/categoryManager'
import * as CategoryImportSummaryGenerator from '@server/modules/category/manager/categoryImportSummaryGenerator'
import { CategoryImportInternalJob } from '@server/modules/category/service/categoryImportJob'

/**
 * Imports the sampling point data combined with the Whisp results (file generated by SamplingPointDataWhispAnalysisJob)
 * into the "sampling_point_data_whisp" category, creating it if it doesn't exist yet.
 */
export default class SamplingPointDataWhispCategoryImportJob extends CategoryImportInternalJob {
  static readonly type = 'SamplingPointDataWhispCategoryImportJob'

  constructor(params?: any) {
    super(params, SamplingPointDataWhispCategoryImportJob.type)
  }

  async getOrCreateSummary() {
    const { whispCategoryFilePath: filePath, numericColumns = [] } = this.context as any
    const defaultLang = Survey.getDefaultLanguage(Survey.getSurveyInfo(this.survey))
    let summary = await CategoryImportSummaryGenerator.createImportSummary({
      filePath,
      fileFormat: FileFormats.csv,
      defaultLang,
    })
    const summaryKeys = new Set(CategoryImportSummary.getItems(summary).map(CategoryImportSummary.getItemKey))
    for (const column of numericColumns) {
      if (!summaryKeys.has(column)) continue
      summary = CategoryImportSummary.assocItemDataType(column, ExtraPropDef.dataTypes.number)(summary)
    }
    return summary
  }

  async _fetchOrCreateCategory() {
    const { surveyId, user, tx } = this
    const categories: Record<string, any> = await CategoryManager.fetchCategoriesAndLevelsBySurveyId(
      { surveyId, draft: true },
      tx
    )
    const existingCategory = Object.values(categories ?? {}).find(
      (category) => Category.getName(category) === Category.samplingPointDataWhispCategoryName
    )
    if (existingCategory) {
      return CategoryManager.fetchCategoryAndLevelsByUuid(
        { surveyId, categoryUuid: Category.getUuid(existingCategory), draft: true, includeValidation: false },
        tx
      )
    }
    const category = Category.newCategory({ [Category.keysProps.name]: Category.samplingPointDataWhispCategoryName })
    return CategoryManager.insertCategory({ user, surveyId, category, system: true }, tx)
  }
}
