version: 0.2

phases:
  install:
    commands:
      - cd RStudioPoolService
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - npm run test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      # Use AWS SAM to package the application by using AWS CloudFormation - sam package command is an alias for the aws cloudformation
      - sam package --template template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-81qiwpvg6puh --output-template template-export.yml
  post_build:
    commands:
      - sam deploy --template-file template-export.yml --stack-name r-studio-pool-service --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - template.yml
    - template-export.yml
