import { create } from './create'

import {
  getCategory,
  getImportSummary,
  getItemActive,
  getItemActiveLastLevelIndex,
  getItemsArray,
  getOnCategoryUpdate,
  isItemsLoading,
  isItemActiveLeaf,
  isCategoryEmpty,
  isCleaned,
  isEditingItemExtraDefs,
} from './read'

import {
  assocCategory,
  assocCategoryProp,
  assocLevelProp,
  assocItemsLoading,
  assocItems,
  assocItem,
  assocItemProp,
  assocItemActive,
  dissocItemActive,
  dissocItemsActive,
  dissocItem,
  dissocItemsLoading,
  dissocItems,
  assocImportSummary,
  assocImportSummaryItemDataType,
  dissocImportSummary,
  assocCleaned,
  assocEditingItemExtraDefs,
} from './update'

export const State = {
  create,

  getCategory,
  getImportSummary,
  isItemsLoading,
  getItemActive,
  getItemActiveLastLevelIndex,
  getItemsArray,
  getOnCategoryUpdate,
  isItemActiveLeaf,
  isCategoryEmpty,
  isCleaned,
  isEditingItemExtraDefs,

  assocCategory,
  assocCategoryProp,
  assocLevelProp,
  assocItemsLoading,
  assocItems,
  assocItem,
  assocItemProp,
  assocItemActive,
  dissocItemActive,
  dissocItemsActive,
  dissocItem,
  dissocItemsLoading,
  dissocItems,
  assocImportSummary,
  assocImportSummaryItemDataType,
  dissocImportSummary,
  assocCleaned,
  assocEditingItemExtraDefs,
}
