#**
#* Load a library if installed, if not it installs it first
#**
usePackage <- function(name) {
  if (!is.element(name, installed.packages()[, 1]))
    install.packages(name, dep = TRUE)
  library(name, character.only = TRUE)
}

usePackage("sqldf")
usePackage("httr")
usePackage("getPass")
usePackage("jsonlite")
usePackage('zip')
usePackage('data.table')
usePackage('RPostgreSQL')
usePackage('srvyr')
usePackage('survey')
usePackage('dplyr')
usePackage('rlang')
# usePackage('car')
# usePackage('reshape')
# usePackage('reshape2')
# usePackage('random')
# usePackage('gsubfn')
# usePackage('desc')
# usePackage('evaluate')
# usePackage('Formula')
# usePackage('knitr')
# usePackage('lazyeval')
# usePackage('locfit')
# usePackage('DataCombine')
# usePackage('RSQLite')
# usePackage('rmarkdown')
# usePackage('XLConnect')
# usePackage('rentrez')
# usePackage('rgbif')
# usePackage('lmfor')
# usePackage('tidyverse')
# usePackage('dismo')
# usePackage('stringi')
# usePackage('survival')
# usePackage('DT')
# usePackage('lattice')
# usePackage('png')
# usePackage('jpeg')
# usePackage('vegan')
# usePackage('sampling')
# usePackage('sp')
# usePackage('markdown')
# usePackage('nortest')
# usePackage('outliers')
# usePackage('raster')
# usePackage('SamplingBigData')
# usePackage('scales')
# usePackage('spatial')
# usePackage('whisker')
# usePackage('sf')
# usePackage('rgdal')
# usePackage('weights')
# usePackage('Hmisc')
# usePackage('mapview')
# usePackage('ggExtra')
# usePackage('BIOMASS')

# usePackage('BiodiversityR') -> there is an error on the load 
