export const surveyCreate = 'survey/create'
export const surveyUpdate = 'survey/update'
export const surveyDelete = 'survey/delete'
export const surveyDefsLoad = 'survey/defs/load'
export const surveyDefsReset = 'survey/defs/reset'
export const surveyChainSave = 'survey/chain/save'
export const surveyChainItemDelete = 'survey/chain/delete'
export const surveyMetaUpdated = 'survey/metadata/updated'
